from infrastructure.models.program_model import Program
from infrastructure.models.course_model import Course
from infrastructure.models.user_model import User
from infrastructure.models.syllabus_model import Syllabus
from infrastructure.models.approval_model import Approval
from infrastructure.models.clo_model import CLO
from infrastructure.models.department_model import Department
from infrastructure.models.plo_model import PLO
from infrastructure.models.role_model import Role
from infrastructure.models.userrole_model import UserRole